backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

display_url: https://www.thelighttreeyoga.co.uk/

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page" }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Main Image",
              name: "mainImage",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                ],
            }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Browser Tab Title", name: "browserTitle", widget: "string"},
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                ],
            }
      - file: "src/pages/home/index.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page" }
          - { 
              label: "Banner Text", 
              name: "bannerText", 
              widget: "list",
              fields: [
                {label: "Item Text", name: "itemText", widget: "string"},
              ],
            }
          - { 
              label: "Section Welcome",
              name: "sectionWelcome",
              widget: "object",
              fields: [
                { label: "Title", name: "title", widget: "string" },
                { label: "Body", name: "body", widget: "markdown" },
                { label: "Image", name: "image", widget: "image" },
                { label: "Image Description", name: "imageAlt", widget: "string" },
                { label: "Quote", name: "quote", widget: "markdown" },
                { label: "Highlighted Text", name: "highlightedText", widget: "string" },
                { 
                  label: "Page Link", 
                  name: "pageLink", 
                  widget: "object",
                  fields: [
                    { label: "Text", name: "text", widget: "string" },
                    { label: "Link URL", name: "linkURL", widget: "string" }
                  ]
                }
              ]
            }
          - {
              label: "Section Schedule",
              name: "sectionSchedule",
              widget: "object",
              fields: [
                { label: "Title", name: "title", widget: "string" },
                { 
                  label: "Classes Timetable", 
                  name: "classesTimetable", 
                  widget: "object",
                  fields: [
                    { label: "Sub Heading", name: "subHeading", widget: "string" },
                    { label: "Body", name: "body", widget: "markdown" }
                  ] 
                },
                { 
                  label: "This Months", 
                  name: "thisMonth", 
                  widget: "object",
                  fields: [
                    { label: "Section Heading", name: "sectionHeading", widget: "string" },
                    { label: "Sub Heading", name: "subHeading", widget: "string" },
                    { label: "Body", name: "body", widget: "markdown" }
                  ] 
                },
                { 
                  label: "Coming Up", 
                  name: "comingUp", 
                  widget: "object",
                  fields: [
                    { label: "Sub Heading", name: "subHeading", widget: "string" },
                    { label: "Body", name: "body", widget: "markdown" }
                  ] 
                },
                { 
                  label: "Page Link", 
                  name: "pageLink", 
                  widget: "object",
                  fields: [
                    { label: "Text", name: "text", widget: "string"},
                    { label: "Link URL", name: "linkURL", widget: "string"}
                  ]
                }
              ]
            }
          - {
              label: "Section My Story",
              name: "sectionMyStory",
              widget: "object",
              fields: [
                { label: "Title", name: "title", widget: "string" },
                { label: "Body", name: "body", widget: "markdown" },
                { label: "Quote", name: "quote", widget: "markdown" },
                { 
                  label: "Page Link", 
                  name: "pageLink", 
                  widget: "object",
                  fields: [
                    { label: "Text", name: "text", widget: "string"},
                    { label: "Link URL", name: "linkURL", widget: "string"}
                  ]
                },
              ]
            }
          - {
              label: "Section Connect",
              name: "sectionConnect",
              widget: "object",
              fields: [
                { label: "Title", name: "title", widget: "string" },
                { 
                  label: "Contact", 
                  name: "contact", 
                  widget: "list", 
                  fields: [
                    { label: "Sub Heading", name: "subHeading", widget: "string" },
                    { label: "Link URL", name: "linkURL", widget: "string" },
                    { label: "Link Text", name: "linkText", widget: "string" }
                  ]
                },
                {
                  label: "Services", 
                  name: "services", 
                  widget: "object", 
                  fields: [
                    { label: "Title", name: "title", widget: "string" },
                    { label: "Sub Heading", name: "subHeading", widget: "string" },
                    { 
                      label: "Service List", 
                      name: "serviceList", 
                      widget: "list",
                      fields: [
                        { label: "Title", name: "title", widget: "string"},
                        { label: "Description", name: "description", widget: "text"},
                        { label: "Image", name: "image", widget: "image"},
                        { label: "Link Text", name: "linkText", widget: "string"},
                        { label: "Link URL", name: "linkURL", widget: "string"}
                      ]
                    }
                  ]
                },
                {
                  label: "Subscribe", 
                  name: "subscribe", 
                  widget: "object", 
                  fields: [
                    { label: "Sub Heading", name: "subHeading", widget: "string" },
                    { label: "Body", name: "body", widget: "markdown" }
                  ]
                }
              ]
            }
          - {
             label: "Section Testimonial",
              name: "sectionTestimonial",
              widget: "object",
              fields: [
                { label: "Title", name: "title", widget: "string" },
                {
                  label: "Testimonial List", 
                  name: "testimonialList",
                  widget: "list",
                  fields: [
                    { label: "description", name: "description", widget: "text" },
                    { label: "author", name: "author", widget: "text" }
                  ] 
                }
              ] 
            }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Browser Tab Title", name: "browserTitle", widget: "string"},
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                ],
            }
      - file: "src/pages/classes/index.md"
        label: "Classes"
        name: "classes"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "classes-page" }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Main Image",
              name: "mainImage",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                ],
            }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Browser Tab Title", name: "browserTitle", widget: "string"},
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                ],
            }
      - file: "src/pages/teachings/index.md"
        label: "Teachings"
        name: "teachings"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "teaching-page" }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Main Image",
              name: "mainImage",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                ],
            }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Browser Tab Title", name: "browserTitle", widget: "string"},
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                ],
            }
  - name: "sections"
    label: "Sections"
    files: 
      - file: "src/pages/introduction/index.md"
        label: "Introduction"
        name: "introduction"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "introduction" }
          - { label: "Title", name: "title", widget: "text"}
          - { label: "Body", name: "body", widget: "markdown"}
          - { label: "Image", name: "image", widget: "image"}
          - { label: "Quote", name: "quote", widget: "markdown"}
          - { label: "Highlighted Text", name: "highlightedText", widget: "text"}
          - { 
              label: "Page Link", 
              name: "pageLink", 
              widget: "object",
              fields: [
                { label: "Link", name: "link", widget: "string" },
                { label: "Label", name: "label", widget: "text" },
              ]
            }
  - name: "navbarAndFooter"
    label: "Navbar & Footer"
    files:
      - file: "src/pages/navbar/index.md"
        label: "Navbar"
        name: "navbar"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "navbar" }
          - {
              label: "Menu Items",
              name: "menuItems",
              widget: "list",
              fields:
                [
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Link Type", name: "linkType", widget: "select", options: ["internal", "external", "hash"] },
                  { label: "Link URL", name: "linkURL", widget: "string", hint: "Use a relative URL (e.g. /about) if the link is an internal link." },
                ],
            }
          - {
              label: "Social Items",
              name: "socialLinks",
              widget: "list",
              fields:
                [
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Social Type", name: "type", widget: string },
                  { label: "Social Link", name: "linkURL", widget: string },
                  { label: "Social Title", name: "hiddenText", widget: string }
                ],
            }
      - file: "src/pages/footer/index.md"
        label: "Footer"
        name: "footer"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "footer" }
          - { label: "Copyright Copy", name: "copyrightText", widget: "string"}
          - {
              label: "Logo Image & Tagline",
              name: "logoImage",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                  { label: "ImageLink", name: "imageLink", widget: "string"}
                ],
            }